### PR TITLE
Groupmsg

### LINKED ISSUE #2474: [FEATURE]Invite new members to join the group, pull the previous history message, expect not to pull the previous message
### OpenIM Server Version

3.5.1

### Operating System and CPU Architecture

Windows (ARM)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

Invite new members to join the group, pull the previous history message, expect not to pull the previous message

### Screenshots Link

_No response_

### PR DESCRIPTION
**Pull request by icey-yu**
## 🅰 Please add the issue ID after "Fixes #"

Fixes #2474
Add enable history for new members.
Refactor enter member notification.

### CODE REVIEW

**Review by FGadvancer — APPROVED** [review]

File: internal/rpc/conversation/conversaion.go [hunk 1]
```diff
@@ -402,6 +402,14 @@ func (c *conversationServer) SetConversationMaxSeq(ctx context.Context, req *pbc
 	return &pbconversation.SetConversationMaxSeqResp{}, nil
 }
 
+func (c *conversationServer) SetConversationMinSeq(ctx context.Context, req *pbconversation.SetConversationMinSeqReq) (*pbconversation.SetConversationMinSeqResp, error) {
+	if err := c.conversationDatabase.UpdateUsersConversationField(ctx, req.OwnerUserID, req.ConversationID,
```
Comment (mo3et) [inline internal/rpc/conversation/conversaion.go:406]: This method is update `conversation` collection. but Seq is save in `seq` collection in DB.

Need check.

@FGadvancer

**Review by mo3et — CHANGES_REQUESTED** [review]

**Comment by mo3et** [comment]
@FGadvancer Need check update field to correct collection.

**Review by mo3et — APPROVED** [review]
