### PR TITLE
fix: fix some bug

### LINKED ISSUE #1711: Bug: fix some bug
### What happened?

1、Resetting a user's password with administrator privileges when the user is still online（/user/password/reset）
2、Getting user information also returns the administrator and system notification number（/user/get_users）
3、Request does not return the added system notification number when adding a system notification number（/user/add_notification_account）
4、Optimize the request body field for getting the system notification number（/user/search_notification_account）
5、Doesn't support getting group member information based on group member nicknames or group member IDs.（/group/get_groups）

### What did you expect to happen?

fix it

### How can we reproduce it (as minimally and precisely as possible)?

Fixing these bugs will result in a smoother experience

### Anything else we need to know?

_No response_

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

### PR DESCRIPTION
**Pull request by luhaoling**
<br>

#### 👀 What this PR does / why we need it:

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

Link: https://github.com/openimsdk/chat/pull/370

#### 🅰 Which issue(s) this PR fixes:

Fixes #1711

### CODE REVIEW

**Review by cubxxw — APPROVED** [review]

File: internal/rpc/user/user.go [hunk 1]
```diff
@@ -228,7 +234,7 @@ func (s *userServer) AccountCheck(ctx context.Context, req *pbuser.AccountCheckR
 }
 
 func (s *userServer) GetPaginationUsers(ctx context.Context, req *pbuser.GetPaginationUsersReq) (resp *pbuser.GetPaginationUsersResp, err error) {
-	total, users, err := s.Page(ctx, req.Pagination)
+	total, users, err := s.PageFindUser(ctx, constant.IMOrdinaryUser, req.Pagination)
```
Comment (AndrewZuo01) [inline internal/rpc/user/user.go:237]: may I know what is IMOrdinaryUser for?

**Review by AndrewZuo01 — APPROVED** [review]

**Review by kubbot — APPROVED** [review]
